language: java
sudo: false
jdk: oraclejdk8
cache:
  directories:
  - $HOME/.m2
script:
  - wget https://raw.githubusercontent.com/pentaho/maven-parent-poms/master/maven-support-files/settings.xml
  - mvn -s settings.xml clean package -pl marketplace-di
