branches:
  only:
    - /^webspoon-.*$/
language: java
sudo: false
jdk: oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
install: true
script:
  - wget https://raw.githubusercontent.com/pentaho/maven-parent-poms/master/maven-support-files/settings.xml
  - mvn -s settings.xml clean source:jar package -pl marketplace-di
before_deploy:
  - git config --local user.name "Hiromu Hota"
  - git config --local user.email "hiromu.hota@hal.hitachi.com"
  - export TRAVIS_TAG=webspoon/nightly
  - git tag $TRAVIS_TAG --force
  - git remote add gh https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  - git push -f gh $TRAVIS_TAG
  - git remote remove gh
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: marketplace-di/target/pentaho-marketplace-di-*.jar
  skip_cleanup: true
  on:
    branch: webspoon-8.2
  name: webSpoon/nightly
  prerelease: true
  overwrite: true
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
